services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: majdeq/gracejeanne-backend:latest
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    expose:
      - "3001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: "https://api.gracejeanne.com"
    image: majdeq/gracejeanne-frontend:latest
    container_name: frontend
    restart: always
    expose:
      - "3000"

  caddy:
    image: caddy:latest
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp" # For HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

volumes:
  caddy_data:
  caddy_config:
